src/WebApplication/Controllers/Admin/AtividadeController.cs
using Domain.Entities;
using Domain.Exceptions;
using Domain.Interfaces.Application;
using System;
using System.Linq;
using System.Web.Mvc;
using WebApplication.Authorize;
using WebApplication.Utils;
using WebApplication.ViewModel;

namespace WebApplication.Controllers.Admin
{
    [CustomAuthorize]
    [RoutePrefix("portal-do-aluno/admin/atividade")]
    public class AtividadeController : Controller
    {
        private readonly IAtividadeAppService _atividadeAppService;
        private readonly IGrupoAppService _grupoAppService;
        private readonly ImageUtil _imageUtil;

        public AtividadeController(IAtividadeAppService atividadeAppService, IGrupoAppService grupoAppService, ImageUtil imageUtil)
        {
            _atividadeAppService = atividadeAppService;
            _grupoAppService = grupoAppService;
            _imageUtil = imageUtil;
        }

        [Route("upload-file")]
        [HttpPost]
        public JsonResult UploadFile()
        {
            var atividadeId = (int)Session["atividadeId"];
            var uploadFileViewModel = new UploadFileViewModel();

            try
            {
                if (Request.Files.AllKeys.Any())
                {
                    var httpPostedFile = Request.Files[0];
                    if (httpPostedFile != null)
                    {
                        uploadFileViewModel.CaminhoDoArquivo = Server.MapPath(string.Format(@"/img/atividades/{0}", atividadeId));
                    }

                    _imageUtil.UploadFoto(httpPostedFile, uploadFileViewModel.CaminhoDoArquivo);

                    uploadFileViewModel.CaminhoDoArquivo = string.Format(@"/img/atividades/{0}/{1}", atividadeId, httpPostedFile.FileName.Replace(" ", "").Trim());
                    uploadFileViewModel.NomeDoArquivo = httpPostedFile.FileName.Replace(" ", "").Trim();
                    uploadFileViewModel.Id = atividadeId;
                }
            }
            catch (Exception ex)
            {
            }

            return Json(uploadFileViewModel, JsonRequestBehavior.AllowGet);
        }

        [Route]
        public ActionResult Index()
        {
            var atividades = _atividadeAppService.GetAll(x => x.Data.Year == 2017).OrderByDescending(x => x.Data).ToList();
            return View("~/Views/PortalDoAluno/Admin/Atividade/Index.cshtml", atividades);
        }

        [Route("{id:int}")]
        public ActionResult AtividadeCadastrar(int id)
        {
            var atividade = new Atividade();
            var path = Server.MapPath(string.Format(@"/img/atividades/{0}", id));

            if (id > 0)
            {
                atividade = _atividadeAppService.Get(id);
                atividade.Fotos = _imageUtil.ListFotoAtividade(path, atividade.Id);
            }
            else
            {
                _imageUtil.ExcluirDiretorioOuFotoAtividade(path, false);
            }

            atividade.Grupos = _grupoAppService.GetAll().OrderBy(x => x.Descricao).ToList();

            Session["atividadeId"] = atividade.Id;

            return View("~/Views/PortalDoAluno/Admin/Atividade/Form.cshtml", atividade);
        }

        [Route("salvar")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Salvar(Atividade atividade)
        {
            var isNew = atividade.Id == 0;

            try
            {
                atividade.EscolaId = 1;
                atividade.Id = _atividadeAppService.SalvarPorApp(atividade);

                if (isNew)
                {
                    var pathDe = Server.MapPath(string.Format(@"/img/atividades/{0}", 0));
                    var pathPara = Server.MapPath(string.Format(@"/img/atividades/{0}", atividade.Id));
                    _imageUtil.RenameFolder(pathDe, pathPara);
                }

                return RedirectToAction("Index");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("excluir")]
        [HttpPost]
        public JsonResult Excluir(Atividade atividade)
        {
            try
            {
                _atividadeAppService.Remove(x => x.Id == atividade.Id);

                var arquivo = Server.MapPath(string.Format(@"/img/atividades/{0}", atividade.Id));
                _imageUtil.ExcluirDiretorioOuFotoAtividade(arquivo, false);

                return Json("sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("excluir-foto")]
        [HttpPost]
        public JsonResult ExcluirFoto(Atividade atividade)
        {
            try
            {
                var arquivo = Server.MapPath(string.Format(@"/img/atividades/{0}/{1}", atividade.Id, atividade.Arquivo));
                _imageUtil.ExcluirDiretorioOuFotoAtividade(arquivo, true);
                return Json("foto removida com sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("selecionar-foto-capa")]
        [HttpPost]
        public JsonResult SelecionarFotoCapa(Atividade atividade)
        {
            try
            {
                _atividadeAppService.SelecionarFotoCapa(atividade);
                return Json("Foto capa selecionada com sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("selecionar-foto-resumo")]
        [HttpPost]
        public JsonResult SelecionarFotoResumo(Atividade atividade)
        {
            try
            {
                _atividadeAppService.SelecionarFotoResumo(atividade);
                return Json("Foto resumo selecionada com sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }
    }
}

src/WebApplication/Controllers/Admin/VideoController.cs
using Domain.Entities;
using Domain.Exceptions;
using Domain.Interfaces.Application;
using System;
using System.Linq;
using System.Web.Mvc;
using WebApplication.Authorize;
using WebApplication.Utils;

namespace WebApplication.Controllers.Admin
{
    [CustomAuthorize]
    [RoutePrefix("portal-do-aluno/admin/video")]
    public class VideoController : Controller
    {
        private readonly IVideoAppService _videoAppService;
        private readonly IGrupoAppService _grupoAppService;

        public VideoController(IVideoAppService videoAppService, IGrupoAppService grupoAppService, ImageUtil imageUtil)
        {
            _videoAppService = videoAppService;
            _grupoAppService = grupoAppService;
        }

        [Route]
        public ActionResult Index()
        {
            var videos = _videoAppService.GetAll().OrderByDescending(x => x.Data).ToList();
            return View("~/Views/PortalDoAluno/Admin/Video/Index.cshtml", videos);
        }

        [Route("{id:int}")]
        public ActionResult VideoCadastrar(int id)
        {
            var video = new Video();
            if (id > 0)
            {
                video = _videoAppService.Get(id);
            }

            video.Grupos = _grupoAppService.GetAll().OrderBy(x => x.Descricao).ToList();

            return View("~/Views/PortalDoAluno/Admin/Video/Form.cshtml", video);
        }

        [Route("salvar")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Salvar(Video video)
        {
            try
            {
                video.EscolaId = 1;
                _videoAppService.Save(video);
                return RedirectToAction("Index");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("excluir")]
        [HttpPost]
        public JsonResult Excluir(Video video)
        {
            try
            {
                _videoAppService.Remove(x => x.Id == video.Id);
                return Json("sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }
    }
}

src/WebApplication/Controllers/SiteController.cs
using Domain.Entities.Email;
using Domain.Exceptions;
using Domain.Interfaces.Application;
using Domain.Interfaces.Email;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using Domain.Entities;
using System.IO;

namespace WebApplication.Controllers
{
    public class SiteController : Controller
    {
        private readonly IAtividadeAppService _atividadeAppService;
        private readonly IGrupoAppService _grupoAppService;
        private readonly IBlogAppService _blogAppService;
        private readonly IVideoAppService _videoAppService;
        private readonly IFaleConoscoService _faleConoscoServiceService;

        public SiteController(IAtividadeAppService atividadeAppService, IVideoAppService videoAppService, IFaleConoscoService faleConoscoServiceService, IBlogAppService blogAppService, IGrupoAppService grupoAppService)
        {
            _atividadeAppService = atividadeAppService;
            _videoAppService = videoAppService;
            _faleConoscoServiceService = faleConoscoServiceService;
            _blogAppService = blogAppService;
            _grupoAppService = grupoAppService;
        }

        [Route]
        public ActionResult Index()
        {
            var atividades = _atividadeAppService.GetAll().OrderByDescending(x => x.Data).ToList();
            var blogs = _blogAppService.GetAll(x => x.Data <= DateTime.Now).OrderByDescending(x => x.Data).Take(8).ToList();
            var videos = _videoAppService.GetAll().OrderByDescending(x => x.Data).Take(5).ToList();

            ViewBag.Atividades = atividades;
            ViewBag.Blogs = blogs;
            ViewBag.Videos = videos;

            return View();
        }

        [Route("sobre")]
        public ActionResult Sobre()
        {
            return View();
        }

        [Route("professor")]
        public ActionResult Professor()
        {
            return View();
        }

        [Route("fale-conosco")]
        public ActionResult FaleConosco()
        {
            return View(new FaleConosco());
        }

        [Route("instagram")]
        public ActionResult Instagram()
        {
            return View();
        }

        [Route("facebook")]
        public ActionResult Facebook()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FaleConoscoEnviar(FaleConosco faleConosco)
        {
            try
            {
                _faleConoscoServiceService.Enviar(faleConosco);

                faleConosco.Alerta = "sucesso";
                return View("FaleConosco", faleConosco);
            }
            catch (CommonException commonException)
            {
                faleConosco.Alerta = "erro";
                return View("FaleConosco", faleConosco);
            }
        }

        [Route("atividades/{grupoId:int?}")]
        public ActionResult Atividades(int grupoId = 0)
        {
            var grupos = _grupoAppService.GetAll().ToList();
            ViewBag.Grupos = grupos;

            var atividades = (grupoId == 0
                ? _atividadeAppService.GetAll(x => x.Data.Year == 2017).OrderByDescending(x => x.Data).ToList()
                : _atividadeAppService.GetAll(x => x.GrupoId == grupoId && x.Data.Year == 2017).OrderByDescending(x => x.Data).ToList());

            return View(atividades);
        }

        [Route("atividade/{link}")]
        public ActionResult Atividade(string link)
        {
            var atividade = _atividadeAppService.GetAll(x => x.Link.ToLower() == link.ToLower()).FirstOrDefault();
            return View(atividade);
        }

        [Route("blog/{link}")]
        public ActionResult Blog(string link)
        {
            var categorias = _blogAppService.GetAll().OrderBy(x => x.Categoria).GroupBy(x => x.Categoria).Select(x => x.Key).ToList();
            ViewBag.Categorias = categorias;

            var blogs = _blogAppService.GetAll(x => x.Data <= DateTime.Now).OrderByDescending(x => x.Data).Take(8).ToList();
            ViewBag.Blogs = blogs;

            var blog = _blogAppService.GetAll(x => x.Link == link).FirstOrDefault();
            return View(blog);
        }

        [Route("blog-por-categoria/{categoria}")]
        public ActionResult BlogPorCategoria(string categoria)
        {
            var categorias = _blogAppService.GetAll().OrderBy(x => x.Categoria).GroupBy(x => x.Categoria).Select(x => x.Key).ToList();
            ViewBag.Categorias = categorias;

            var blogs = _blogAppService.GetAll(x => x.Data <= DateTime.Now && (x.Categoria == categoria || categoria == "todas")).OrderByDescending(x => x.Data).ToList();
            return View(blogs);
        }

        [Route("blog-por-tag/{tag}")]
        public ActionResult BlogPorTag(string tag)
        {
            var categorias = _blogAppService.GetAll().OrderBy(x => x.Categoria).GroupBy(x => x.Categoria).Select(x => x.Key).ToList();
            ViewBag.Categorias = categorias;

            var blogs = _blogAppService.GetAll(x => x.Data <= DateTime.Now && x.Tag.Contains(tag)).OrderByDescending(x => x.Data).ToList();
            return View("BlogPorCategoria", blogs);
        }

        [Route("videos")]
        public ActionResult Videos(string tag)
        {
            var videos = _videoAppService.GetAll().OrderByDescending(x => x.Data).ToList();
            return View(videos);
        }

        [Route("fotos")]
        public ActionResult Fotos()
        {
            List<string> fotosNomes = new List<string>(0);
            string[] fotos = Directory.GetFiles(Server.MapPath("/img/fotos"));
            foreach (var foto in fotos)
            {
                var index = foto.IndexOf("img");
                fotosNomes.Add(foto.Substring(index));
            }

            return View(fotosNomes);
        }

        [Route("programa-bilingue")]
        public ActionResult ProgramaBilingue()
        {
            return View("ProgramaBilingue");
        }
    }
}

src/WebApplication/Views/Site/Blog.cshtml
@model Domain.Entities.Blog

@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.MetaDescription = Model.MetaDescription;
    ViewBag.BlogTitulo = "VEJA TAMBÉM";
}

@section Head{
    <meta name="twitter:card" content="@Model.MetaTitle" />
    <meta name="twitter:site" content="@string.Format("@EcoAprender")" />
    <meta name="twitter:title" content="@Model.MetaTitle" />
    <meta name="twitter:description" content="@Model.MetaDescription" />
    <meta name="twitter:image" content="http://www.ecoaprender.com.br/img/blog/@Model.FotoCapa" />

    <meta property="og:type" content="website" />
    <meta property="og:locale" content="pt_BR">
    <meta property="og:url" content="@Request.Url.AbsoluteUri">
    <meta property="og:title" content="@Model.MetaTitle">
    <meta property="og:site_name" content="Escola Eco Aprender">
    <meta property="og:description" content="@Model.MetaDescription">
    <meta property="og:image" content="http://www.ecoaprender.com.br/img/blog/@Model.FotoCapa">
    <meta property="og:image:url" content="http://www.ecoaprender.com.br/img/blog/@Model.FotoResumo">
}

<section id="main">

    <header>
        <img src="~/img/blog/@Model.FotoCapa" class="img-responsive img-principal" alt="Escola de Educação Infantil e Berçário Eco Aprender" itemprop="image" />
    </header>

    <section id="navegacao-header" class="div-veja-mais MarginTop30">
        <nav class="container">
            <ul>
                <li><a rel="nofollow" href="@Url.Action("index", "Site")" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                <li><a href="#" title="@Model.Titulo" itemprop="name">@Model.Titulo</a></li>
            </ul>
        </nav>
    </section>

    <div class="row">
        <div class="container pagina-interna">
            <article id="blog" class="col-xs-12 col-md-8" itemscope itemtype="http://schema.org/BlogPosting">
                <meta itemprop="keywords" content="Escola, Educação Infantil, Berçário, Tatuapé, @Model.Categoria" />
                <meta itemprop="author" content="Fernando José" />
                <meta itemprop="datePublished" content="@Model.DataInclusao" />
                <meta itemprop="dateModified" content="@Model.DataAlteracao" />

                <div class="hide" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
                    <span itemprop="name">
                        Escola de Educação Infantil e Berçário Eco Aprender
                    </span>
                    <div itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
                        <img itemprop="url" src="~/img/logo-eco-aprender.jpg" />
                    </div>
                </div>

                <header><h2 class="texto-escuro titulo-mobile" itemprop="name headline mainEntityOfPage">@Model.Titulo</h2></header>
                <div itemprop="description">@Html.Raw(Model.Completa)</div>
            </article>

            <div class="col-xs-12 col-md-4 categorias-e-tags">
                <section id="categorias">
                    <div class="row">
                        <div class="col-xs-12 div-blog-categorias">
                            <h2 class="blog-anuncio-h2">Categorias</h2>
                            <ul>
                                @foreach (var categoria in ViewBag.Categorias)
                                {
                                    <li>
                                        <a href="/blog-por-categoria/@categoria" title="@categoria">
                                            <h3>
                                                @categoria
                                            </h3>
                                        </a>
                                    </li>
                                }

                                <li>
                                    <a href="/blog-por-categoria/todas" title="Categorias">
                                        <h3>
                                            Todas categorias
                                        </h3>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>

                <section id="tags" class="margin-top-30">
                    <div class="row">
                        <div class="col-xs-12 div-blog-tags">
                            <h2 class="blog-anuncio-h2">Tags</h2>
                            <ul>
                                @foreach (var tag in Model.Tag.Split(','))
                                {
                                    <li>
                                        <h2>
                                            <a href="/blog-por-tag/@tag" title="@tag" class="btn btn-saiba-mais-orange">
                                                @tag
                                            </a>
                                        </h2>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    @Html.Partial("_Blog")

    <section id="redes-sociais" class="redes-sociais-compartilhar background-branco">
        <section id="share" class="container">
            <div class="col-xs-12 anuncio-compartilhe">
                <header class="col-xs-12 compartilhe-titulo">
                    <i class="fa fa-angle-down"></i>
                    <span>COMPARTILHE ESTA MATÉRIA COM SEUS AMIGOS</span>
                </header>

                <div class="col-xs-12 icones">
                    <i class="spr-detalhes-anuncio ico-facebook"></i>

                    <a href="#" onclick="twitter = window.open('https://twitter.com/share', 'Twitter', width = 600, height = 150); return false;">
                        <i class="spr-detalhes-anuncio ico-twitter"></i>
                    </a>
                    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>

                    <a href="#" onclick="googlePlus = window.open('https://plus.google.com/share?url=@Request.Url', 'GooglePlus', width = 600, height = 150); return false;">
                        <i class="spr-detalhes-anuncio ico-gplus"></i>
                    </a>
                </div>
            </div>
        </section>

        <section id="comentario" class="container margin-top-46">
            <div class="row">
                <div class="col-xs-12">
                    <div id="disqus_thread"></div>
                    <script>
                        var disqus_config = function () {
                            this.page.url = "@Request.Url";
                            this.page.identifier = "@Model.Id";
                        };

                        (function () {
                            var d = document, s = d.createElement('script');
                            s.src = '//ecoaprender.disqus.com/embed.js';
                            s.setAttribute('data-timestamp', +new Date());
                            (d.head || d.body).appendChild(s);
                        })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
                    <script id="dsq-count-scr" src="//carspremium.disqus.com/count.js" async></script>
                </div>
            </div>
        </section>
    </section>

    <section id="navegacao-footer" class="div-veja-mais MarginTop30">
        <nav class="container">
            <ul>
                <li><a rel="nofollow" href="@Url.Action("index", "Site")" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                <li><a href="#" title="@Model.Titulo" itemprop="name">@Model.Titulo</a></li>
            </ul>
        </nav>
    </section>
</section>

<input type="hidden" id="facebookName" value="@Model.Titulo" />
<input type="hidden" id="facebookLink" value="@Request.Url" />
<input type="hidden" id="facebookPicture" value="http://www.ecoaprender.com.br/img/blog/@Model.FotoCapa" />
<input type="hidden" id="facebookCaption" value="@Model.MetaTitle" />
<input type="hidden" id="facebookDescription" value="@Model.Titulo" />
<input type="hidden" id="facebookMessage" value="@Model.MetaDescription" />

<div id="fb-root"></div>

@section scripts{
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '998622546846492',
                xfbml: true,
                version: 'v2.5',
                status: true,
                cookie: true
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pt_BR/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    @Scripts.Render("~/bundles/atividade")
    @Scripts.Render("~/bundles/blog")
}

src/WebApplication/Views/Site/BlogPorCategoria.cshtml
@model List<Domain.Entities.Blog>

@{
    ViewBag.Title = "Escola Infantil e Berçário Eco Aprender - Blog";
    ViewBag.MetaDescription = "Este blog fala sobre assuntos relacionados a escola, data comemorativas e curiosidades";
}

<section id="main" itemscope itemtype="http://schema.org/Blog">

    <header>
        <img src="~/img/header-blog.jpg" class="img-responsive img-principal" alt="Blog da Escola Eco Aprender" itemprop="image" />
    </header>

    <section id="navegacao-header" class="div-veja-mais MarginTop30">
        <nav class="container">
            <ul>
                <li><a rel="nofollow" href="@Url.Action("index", "Site")" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                <li><a href="/blog-por-categoria/todas" title="Todas" itemprop="name">Todas</a><i class="fa fa-angle-right"></i></li>
                @foreach (var categoria in ViewBag.Categorias)
                {
                    <li><a href="/blog-por-categoria/@categoria" title="@categoria">@categoria</a><i class="fa fa-angle-right"></i></li>
                }
            </ul>
        </nav>
    </section>

    <div class="container pagina-interna" id="homeBlog">
        <div class="row">
            @foreach (var blog in Model)
            {
                <article class="col-xs-12 col-md-4 todos-blogs" itemscope itemtype="http://schema.org/BlogPosting">
                    <meta itemprop="keywords" content="Escola, Educação Infantil, Berçário, Tatuapé, @blog.Categoria" />
                    <meta itemprop="author" content="Fernando José" />
                    <meta itemprop="datePublished" content="@blog.DataInclusao" />
                    <meta itemprop="dateModified" content="@blog.DataAlteracao" />

                    <div class="hide" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
                        <span itemprop="name">
                            Escola de Educação Infantil e Berçário Eco Aprender
                        </span>
                        <div itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
                            <img itemprop="url" src="~/img/logo-eco-aprender.jpg" />
                        </div>
                    </div>

                    <header>
                        <figure itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
                            <img src="/img/blog/@blog.FotoResumo" class="img-responsive" title="@blog.Titulo" alt="@blog.Titulo" itemprop="url" />
                            <meta itemprop="width" content="550">
                            <meta itemprop="height" content="400">
                        </figure>
                    </header>
                    <h2 itemprop="headline mainEntityOfPage">@blog.Titulo</h2>
                    <div itemprop="description" class="resumo">@Html.Raw(blog.Resumo)</div>
                    <a href="/Blog/@blog.Link" itemprop="url" class="btn btn-saiba-mais-orange">VEJA MAIS</a>
                </article>
            }
        </div>
    </div>
</section>

src/WebApplication/Views/Site/Fotos.cshtml
@model List<string>

@{
    ViewBag.Title = "Escola Infantil e Berçário Eco Aprender - Vídeos";
    ViewBag.MetaDescription = "Estas fotos mostram os alunos da escola Eco Aprender fazendo as atividades do dia a dia na escola";
}

<section id="main">

    <header>
        <img src="~/img/fotos.jpg" class="img-responsive img-principal" alt="Escola de Educação Infantil e Berçário Eco Aprender" itemprop="image" />
    </header>

    <section id="navegacao-header" class="div-veja-mais MarginTop30">
        <nav class="container">
            <ul>
                <li><a rel="nofollow" href="@Url.Action("index", "Site")" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                <li><a href="/fotos" title="Fotos" itemprop="name">Fotos</a><i class="fa fa-angle-right"></i></li>
            </ul>
        </nav>
    </section>

    <div class="gallery" id="gallery" style="width: 90%; text-align: center">

        @foreach (var foto in Model)
        {
            <div class="mb-3 pics animation all 2">
                <img class="img-fluid" src="~/@foto" alt="Fotos da escola Eco Aprender" style="border: 2px solid white; max-width: 200px">
            </div>
        }

    </div>

</section>

src/WebApplication/Views/Site/Videos.cshtml
@model List<Domain.Entities.Video>

@{
    ViewBag.Title = "Escola Infantil e Berçário Eco Aprender - Vídeos";
    ViewBag.MetaDescription = "Estes videos mostram os alunos do infantil fazendo as atividades do dia a dia na escola";
}

<section id="main">

    <header>
        <img src="~/img/header-videos.jpg" class="img-responsive img-principal" alt="Escola de Educação Infantil e Berçário Eco Aprender" itemprop="image" />
    </header>

    <section id="navegacao-header" class="div-veja-mais MarginTop30">
        <nav class="container">
            <ul>
                <li><a rel="nofollow" href="@Url.Action("index", "Site")" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                <li><a href="/videos" title="Videos" itemprop="name">Videos</a><i class="fa fa-angle-right"></i></li>
            </ul>
        </nav>
    </section>

    <div class="container pagina-interna">
        <div class="row">
            @foreach (var video in Model)
            {
                <article class="col-xs-12 col-md-4 todos-blogs" itemscope itemtype="http://schema.org/VideoObject">
                    <meta itemprop="embedURL" content="http://www.youtube.com/watch?v=@video.Embed" />
                    <meta itemprop="uploadDate" content="@video.DataInclusao" />
                    <meta itemprop="thumbnailUrl" content="http://www.ecoaprender.com.br/img/header-videos.jpg" />

                    <header>
                        <iframe src="https://www.youtube.com/embed/@video.Embed" frameborder="0" allowfullscreen class="player"></iframe>
                    </header>
                    <h2 itemprop="name">@video.Titulo</h2>
                    <div itemprop="description" class="text-justify">@Html.Raw(video.Descricao)</div>
                </article>
            }
        </div>
    </div>
</section>