src/WebApplication/Controllers/PortalDoAlunoController.cs
using Domain.Entities;
using Domain.Exceptions;
using Domain.Interfaces.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApplication.Authorize;

namespace WebApplication.Controllers
{
    [CustomAuthorize]
    [RoutePrefix("portal-do-aluno")]
    public class PortalDoAlunoController : Controller
    {
        private readonly IUsuarioAppService _usuarioAppService;
        private readonly IComunicadoAppService _comunicadoAppService;

        public PortalDoAlunoController(IUsuarioAppService usuarioAppService, IComunicadoAppService comunicadoAppService)
        {
            _usuarioAppService = usuarioAppService;
            _comunicadoAppService = comunicadoAppService;
        }

        [AllowAnonymous]
        [Route]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [Route("login/{login}/{senha}")]
        [HttpGet]
        public JsonResult Login(string login, string senha)
        {
            try
            {
                var usuario = _usuarioAppService.Login(login, senha);

                Session.Add("UsuarioId", usuario.Id);
                Session.Add("UsuarioLogin", usuario.Login);
                Session.Add("UsuarioNome", usuario.Nome);
                Session.Add("UsuarioPerfilId", usuario.PerfilId);
                Session.Add("UsuarioFoto", usuario.Foto);

                //--- OAuth
                FormsAuthentication.SetAuthCookie(usuario.Login, true);

                return Json("sucesso", JsonRequestBehavior.AllowGet);
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error, JsonRequestBehavior.AllowGet);
            }
        }

        [Route("painel")]
        public ActionResult Painel()
        {
            var comunicados = _comunicadoAppService.GetAll().OrderByDescending(x => x.Id).Take(8).ToList();
            ViewBag.Comunicados = comunicados;

            ViewBag.UsuarioNome = Session["UsuarioNome"] ?? "";
            ViewBag.UsuarioFoto = Session["UsuarioFoto"] != null && !string.IsNullOrEmpty(Session["UsuarioFoto"].ToString()) ? Session["UsuarioFoto"] : "logo-eco-aprender.jpg";

            return View();
        }

        [Route("sair")]
        public ActionResult Sair()
        {
            //--- Clears out Session
            Session.Clear();
            Session.Abandon();

            //--- Signs out of WebSecurity and FormsAuthentication
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "");
        }

        [Route("usuario")]
        public ActionResult Usuario()
        {
            var usuarios = _usuarioAppService.GetAll(x => x.EscolaId == 1).OrderBy(x => x.Nome).ToList();
            ViewBag.Usuarios = usuarios;

            return View(usuarios);
        }

        [Route("usuario/{login}")]
        public ActionResult UsuarioCadastrar(string login)
        {
            var usuario = new Usuario();
            if (login.ToLower() != "novo")
            {
                usuario = _usuarioAppService.GetAll(x => x.Login == login).FirstOrDefault();
                usuario.UsuarioNome = Session["UsuarioNome"].ToString();
            }

            return View(usuario);
        }

        [Route("usuario-salvar")]
        [HttpPost]
        public JsonResult UsuarioSalvar(Usuario usuario)
        {
            try
            {
                usuario.EscolaId = 1;
                _usuarioAppService.Save(usuario);
                return Json("sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }

        [Route("usuario-excluir")]
        [HttpPost]
        public JsonResult UsuarioExcluir(Usuario usuario)
        {
            try
            {
                _usuarioAppService.Remove(x => x.Id == usuario.Id);
                return Json("sucesso");
            }
            catch (CommonException commonException)
            {
                return Json(commonException.Error);
            }
        }
    }
}

src/WebApplication/Views/PortalDoAluno/Index.cshtml
@{
    ViewBag.Title = "Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender";
    ViewBag.MetaDescription = "No portal do aluno da Escola Eco Aprender, os pais e alunos da escola tem acesso ao conteúdo programático, comunicados e ao cardápio.";
}

<img src="/img/portal-do-aluno/portal-do-aluno-header.jpg" class="img-responsive img-principal" title="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" alt="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" />

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno" title="Portal do Aluno">Portal do Aluno</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container pagina-interna">
    <div class="row">

        <div class="col-xs-12 col-md-6">
            <h2>Login para acessar o <strong>Portal do Aluno</strong></h2>

            <form class="form-horizontal" id="form" name="form" method="get" action="@Url.Action("Login", "Portal-Do-Aluno")">
                <div class="form-group">
                    <label for="Login" class="col-xs-2 control-label">Login</label>
                    <div class="col-xs-10">
                        <input type="text" class="form-control" name="login" id="login" />
                    </div>
                </div>

                <div class="form-group">
                    <label for="Senha" class="col-xs-2 control-label">Senha</label>
                    <div class="col-xs-10">
                        <input type="password" class="form-control" name="senha" id="senha" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-offset-2 col-xs-10">
                        <button type="submit" class="btn btn-primary btn-salvar" id="entrar">Entrar</button>
                    </div>
                </div>

                <p class="col-xs-offset-2 col-xs-10 alerta alerta-login hide" id="mensagemDeErro">
                    Usuário ou Senha não encontrado!
                </p>
            </form>
        </div>
        <div class="col-xs-12 col-md-6">
            <h2>Tenha <strong>acesso ao conteúdo completo</strong> que inclui:</h2>
            <p class="texto-escuro">
                <ul>
                    <li><h3>Comunicados;</h3></li>
                    <li><h3>Conteúdo Programático;</h3></li>
                    <li><h3>Cardápio elaborado pela nossa nutricionista.</h3></li>
                </ul>
            </p>
        </div>
    </div>
</div>

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno" title="Portal do Aluno">Portal do Aluno</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="actionPainel" value="@Url.Action("Painel", "PortalDoAluno")" />

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
    @Scripts.Render("~/bundles/portal-do-aluno")
}

src/WebApplication/Views/PortalDoAluno/Painel.cshtml
@{
    ViewBag.Title = "Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender";
    ViewBag.MetaDescription = "No portal do aluno da Escola Eco Aprender, os pais e alunos da escola tem acesso ao conteúdo programático, comunicados e ao cardápio.";

    var usuarioNome = Session["UsuarioNome"] != null ? Session["UsuarioNome"].ToString().ToUpper() : "";
    var usuarioFoto = Session["UsuarioFoto"] != null && !string.IsNullOrEmpty(Session["UsuarioFoto"].ToString()) ? Session["UsuarioFoto"].ToString().ToUpper() : "logo-eco-aprender.jpg";
}

<input type="text" id="isAdmin" value="true" class="hide" />

<div class="home-frase header-portal-do-aluno titulo-desktop">
    <h2 class="texto-branco">@usuarioNome BEM VINDO AO PORTAL DO ALUNO DA ESCOLA <strong>ECO APRENDER</strong></h2>
</div>

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Painel" title="Painel">Painel</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container portal-do-aluno">
    <div class="row">

        <div class="col-xs-12 col-md-7">

            <div class="row">
                <div class="col-xs-12">
                    <p style="font-weight: bold">Reunião de Pais</p>
                    <p>
                        <img alt="Reunião de Pais" title="Reunião de Pais" src="~/img/portal-do-aluno/reuniao-pais-2018.jpg" class="img img-responsive" />
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <p style="font-weight: bold">Sobre a parceria da Escola Eco Aprender com a 2 Ways e detalhes do brograma bilíngue</p>
                    <ul>
                        <li><a href="~/Content/projeto-bilingue/apresentacao-2-ways-projeto-bilingue.pptx">Fazer o download do material usado na apresentação (PowerPoint)</a></li>
                        <li>
                            Vídeos da apresentação

                            <ul>
                                <li><a href="https://youtu.be/5SBHx4gbLgU" target="_blank">Parte 1</a></li>
                                <li><a href="https://youtu.be/xCaOeFgd2d8" target="_blank">Parte 2</a></li>
                                <li><a href="https://youtu.be/eBXR6_L1_-E" target="_blank">Parte 3</a></li>
                                <li><a href="https://youtu.be/rKvikQYachs" target="_blank">Parte 4</a></li>
                                <li><a href="https://youtu.be/M-G3VWmQMZY" target="_blank">Parte 5</a></li>
                                <li><a href="https://youtu.be/BwsW8GEvE9E" target="_blank">Parte 6</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="row margin-top-60">
                <div class="col-xs-12">
                    @Html.Partial("_Comunicado")
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 margin-top-60">
                    <p><strong>Cardápio - </strong>Acompanhe o que nossos pequenos estão comendo, clique no link abaixo para abrir o cardápio da turma desejada.</p>
                </div>
            </div>

            <div class="row margin-top-30">
                <div class="col-xs-3 cardapio">
                    <a href="/Content/Cardapio/cardapio-bercario.pdf" target="_blank">
                        <img src="~/img/cardapio-bercario.jpg" class="img-responsive img-circle" alt="Berçário" title="Berçário" />
                    </a>
                </div>
                <div class="col-xs-3 cardapio">
                    <a href="/Content/Cardapio/cardapio-grupo-1.pdf" target="_blank">
                        <img src="~/img/cardapio-grupo-1.jpg" class="img-responsive img-circle" alt="Grupo 1" title="Grupo 1" />
                    </a>
                </div>
                <div class="col-xs-3 cardapio">
                    <a href="/Content/Cardapio/cardapio-grupos.pdf" target="_blank">
                        <img src="~/img/cardapio-grupo-2.jpg" class="img-responsive img-circle" alt="Grupo 2" title="Grupo 2" />
                    </a>
                </div>
                <div class="col-xs-3 cardapio">
                    <a href="/Content/Cardapio/cardapio-grupos.pdf" target="_blank">
                        <img src="~/img/cardapio-grupo-345.jpg" class="img-responsive img-circle" alt="Grupo 3, 4 e 5" title="Grupo 3, 4 e 5" />
                    </a>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-1 col-linha-vertical">
            &nbsp;
        </div>

        <div class="col-xs-12 col-md-4">
            <div class="row">
                <div class="col-xs-12">
                    <img src="~/img/@usuarioFoto" class="img-responsive foto-capa" alt="@usuarioNome" title="@usuarioNome" />
                </div>
            </div>
        </div>

    </div>
</div>

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Painel" title="Painel">Painel</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/comunicado")
    @Scripts.Render("~/bundles/bootbox")
}

src/WebApplication/Views/PortalDoAluno/Usuario.cshtml
@{
    ViewBag.Title = "Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender";
    ViewBag.MetaDescription = "No portal do aluno da Escola Eco Aprender, os pais e alunos da escola tem acesso ao conteúdo programático, comunicados e ao cardápio.";
}

<input type="text" id="isAdmin" value="true" class="hide" />

<div class="home-frase alpha60 titulo-desktop">
    <h2 class="texto-branco">USUÁRIOS DA ESCOLA DE EDUCAÇÃO INFANTIL E BERÇÁRIO <strong>ECO APRENDER</strong></h2>
</div>
<img src="/img/portal-do-aluno/portal-do-aluno-header.jpg" class="img-responsive img-principal" title="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" alt="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" />

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Painel" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Usuario" title="Usuários">Usuários</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container pagina-interna">

    <div class="row" id="lista-usuario">

        <div class="col-xs-12">

            <table class="table table-hover table-data" id="usuarios">
                <thead>
                    <tr>
                        <th colspan="3">Lista de <strong>Usuários</strong></th>
                    </tr>
                    <tr>
                        <th>Nome</th>
                        <th>Login</th>
                        <th>Email</th>
                        <th>Celular</th>
                        <th></th>
                        <th><a href="/Portal-Do-Aluno/Usuario/Novo" class="btn btn-primary novo">Novo</a></th>
                    </tr>
                </thead>
                <tbody>

                    @{
                        var usuarios = ViewBag.Usuarios;

                        if (usuarios != null)
                        {
                            foreach (var usuario in usuarios)
                            {
                                <tr>
                                    <td>@usuario.Nome</td>
                                    <td>@usuario.Login</td>
                                    <td>@usuario.Email</td>
                                    <td>@usuario.TelefoneCelular</td>
                                    <td>
                                        <a href="/Portal-Do-Aluno/Usuario/@usuario.Login" class="btn btn-success editar">Editar</a>
                                    </td>
                                    <td>
                                        <button class="btn btn-danger excluir" onclick="usuario.Excluir(@usuario.Id)">Excluir</button>
                                    </td>
                                </tr>
                            }
                        }
                    }

                </tbody>
            </table>

        </div>

    </div>
</div>

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Painel" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Usuario" title="Usuários">Usuários</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="actionPainel" value="@Url.Action("Painel", "PortalDoAluno")" />

@section scripts{
    <script src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
    @Scripts.Render("~/bundles/bootbox")
    @Scripts.Render("~/bundles/usuario")
}

src/WebApplication/Views/PortalDoAluno/UsuarioCadastrar.cshtml
@model Domain.Entities.Usuario

@{
    ViewBag.Title = "Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender";
    ViewBag.MetaDescription = "No portal do aluno da Escola Eco Aprender, os pais e alunos da escola tem acesso ao conteúdo programático, comunicados e ao cardápio.";
}

<input type="text" id="isAdmin" value="true" class="hide" />

<div class="home-frase alpha60 titulo-desktop">
    <h2 class="texto-branco">USUÁRIOS DA ESCOLA DE EDUCAÇÃO INFANTIL E BERÇÁRIO <strong>ECO APRENDER</strong></h2>
</div>
<img src="/img/portal-do-aluno/portal-do-aluno-header.jpg" class="img-responsive img-principal" title="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" alt="Portal do Aluno da Escola de Educação Infantil e Berçário Eco Aprender" />

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Painel" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Usuario" title="Usuários">Usuários</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container pagina-interna">

    <div class="row">

        <div class="col-xs-12">
            <h2>Cadastro de <strong>Usuário</strong></h2>

            <form class="form-horizontal" id="form" name="form" method="post" action="@Url.Action("Usuario-Salvar", "Portal-Do-Aluno")">
                <div class="form-group">
                    <label for="Nome" class="col-xs-2 control-label">Nome</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Id, new { @class = "hide" })
                        @Html.TextBoxFor(x => x.UsuarioNome, new { @class = "hide" })
                        @Html.TextBoxFor(x => x.Nome, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2 control-label">Nome no Boleto</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.NomeNoBoleto, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Login" class="col-xs-2 control-label">Login</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Senha" class="col-xs-2 control-label">Senha</label>
                    <div class="col-xs-5">
                        @Html.PasswordFor(x => x.Senha, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Email" class="col-xs-2 control-label">Email</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @type = "email" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Telefone" class="col-xs-2 control-label">Telefone</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.TelefoneResidencial, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Celular" class="col-xs-2 control-label">Celular</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.TelefoneCelular, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="Aniversário" class="col-xs-2 control-label">Aniversário</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.DataDeAniversario, new { @class = "form-control", @type = "datetime" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2 control-label">CPF</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Cpf, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2 control-label">Endereço</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Endereco, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2 control-label">Bairro</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Bairro, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-xs-2 control-label">Cep</label>
                    <div class="col-xs-5">
                        @Html.TextBoxFor(x => x.Cep, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-offset-2 col-xs-10">
                        <button type="submit" class="btn btn-primary btn-salvar" id="salvar">Salvar</button>
                        <a href="/Portal-Do-Aluno/Usuario" type="button" class="btn btn-warning">Voltar</a>
                    </div>
                </div>

                <p class="col-xs-offset-2 col-xs-10 alerta alerta-login hide" id="mensagemDeErro">

                </p>
            </form>
        </div>

    </div>
</div>

<div class="div-veja-mais MarginTop30">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li><a href="/" title="Escola de Educação Infantil e Berçário Eco Aprender">Escola de Educação Infantil e Berçário Eco Aprender</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Painel" title="Portal do Aluno">Portal do Aluno</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/Portal-Do-Aluno/Usuario" title="Usuários">Usuários</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="actionPainel" value="@Url.Action("Painel", "PortalDoAluno")" />

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
    @Scripts.Render("~/bundles/usuarioCadastrar")
}